### ISSUE TITLE
Parameters update during test time

### ISSUE THREAD

**Issue by xuyingzhongguo** [yueatsprograms/ttt_cifar_release#8]
Hello!
Maybe this is a stupid question, but I could not find where the parameters are updated in the test time. 
Could you please point them for me?
Thank you!

**Comment by yueatsprograms** [comment]
Here: https://github.com/yueatsprograms/ttt_cifar_release/blob/acac817fb7615850d19a8f8e79930240c9afe8b5/test_calls/test_adapt.py#L58

**Comment by xuyingzhongguo** [comment]
> Here:
> 
> https://github.com/yueatsprograms/ttt_cifar_release/blob/acac817fb7615850d19a8f8e79930240c9afe8b5/test_calls/test_adapt.py#L58

Thank you for the reply!
So actually test_initial.py is the test results without test time training right?
